spring:
    datasource:
        driver-class-name: com.mysql.cj.jdbc.Driver
        password: ''
        url: jdbc:mysql://localhost:3306/springboot
        username: root
    jpa:
        database-platform: org.hibernate.dialect.MySQLDialect
        hibernate:
            ddl-auto: create
        show-sql: true
    profiles:
        active: dev


---
server:
    port: 9090
spring:
    application:
        name: SPRING-BOOT-APP-DEV
    config:
        activate:
            on-profile: dev
---
spring:
    application:
        name: SPRING-BOOT-APP-PROD
    config:
        activate:
            on-profile: prod
server:
    port: 9091

